package backend.app.premier_chat.Models.enums;

public enum TokenType {
    ACCESS_TOKEN,
    REFRESH_TOKEN,
    WS_ACCESS_TOKEN,
    WS_REFRESH_TOKEN,
    PRE_AUTHORIZATION_TOKEN,
    ACTIVATION_TOKEN,
    PHONE_NUMBER_VERIFICATION_TOKEN,
    EMAIL_VERIFICATION_TOKEN
}
